### ISSUE TITLE
Broken Images

### ISSUE THREAD

**Issue by adameckerle** [RoxieAtRubrik/camp-rubrik-microsoft#4]
**Describe the bug**
All images within the lab guide are broken.

**To Reproduce**
No steps to reproduce, taking a look at the Camp Rubrik lab guide on GitBook is enough to acknowledge the issue.

**Expected behavior**
All pictures and screenshots should be re-added

**Screenshots**
![image](https://user-images.githubusercontent.com/16551791/97934064-8fa60000-1d42-11eb-89b5-331d133f1060.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
OS: MacOS, Windows
Browser: Tested on Safari, Chrome, Firefox and Edge on MacOS and on Chrome, Firefox and Edge on Windows 10
Version: latest

**Comment by RoxieAtRubrik** [comment]
Resolved, yay!
